name: Build and Deploy Backend to EC2 via Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: set_image_tag
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=staging-${GITHUB_SHA}" >> $GITHUB_ENV
          fi

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image (Production)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: |
            maathre/maathre-backend:${{ env.IMAGE_TAG }}
            maathre/maathre-backend:latest

      - name: Deploy on EC2 (Production)
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo docker container prune -f
            sudo docker image prune -af
            sudo docker volume prune -f

            sudo docker stop maathre-backend-prod || true
            sudo docker rm maathre-backend-prod || true

            sudo docker pull maathre/maathre-backend:${{ env.IMAGE_TAG }}

            sudo docker run -d --name maathre-backend-prod -p 8000:8000 \
              -e SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
              -e SUPABASE_SERVICE_ROLE_KEY="${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
              -e SUPABASE_ANON_KEY="${{ secrets.SUPABASE_ANON_KEY }}" \
              -e SUPABASE_JWT_SECRET="${{ secrets.SUPABASE_JWT_SECRET }}" \
              -e RAZORPAY_KEY_ID="${{ secrets.RAZORPAY_KEY_ID }}" \
              -e RAZORPAY_KEY_SECRET="${{ secrets.RAZORPAY_KEY_SECRET }}" \
              -e RAZORPAY_WEBHOOK_SECRET="${{ secrets.RAZORPAY_WEBHOOK_SECRET }}" \
              -e PROKERALA_CLIENT_ID="${{ secrets.PROKERALA_CLIENT_ID }}" \
              -e PROKERALA_CLIENT_SECRET="${{ secrets.PROKERALA_CLIENT_SECRET }}" \
              maathre/maathre-backend:${{ env.IMAGE_TAG }}

      